version: '3.8'
services:
  mysql_test:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test_patient_db
    ports:
      - '3308:3306'
