version: '3.8'
services:
  mysql_dev:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: patient_db
    ports:
      - '3307:3306'
